#!/usr/bin/env bash
set -euo pipefail

DATA_FILE="${LONGMEMEVAL_DATA:-data/longmemeval_s_cleaned.json}"
OUTPUT_DIR="${LONGMEMEVAL_OUTPUT_DIR:-experiments/public_results/longmemeval}"
SPLIT_LABEL="${LONGMEMEVAL_SPLIT_LABEL:-longmemeval_s_cleaned}"
ANSWER_MODEL="${OPENAI_MODEL:-gpt-4o-mini}"
EXTRACTION_MODEL="${LONGMEMEVAL_EXTRACTION_MODEL:-$ANSWER_MODEL}"
JUDGE_MODEL="${LONGMEMEVAL_JUDGE_MODEL:-gpt-4o}"
SAMPLE_SIZE="${LONGMEMEVAL_SAMPLE_SIZE:-50}"
SAMPLE_SEED="${LONGMEMEVAL_SAMPLE_SEED:-20260421}"
MAX_SESSIONS="${LONGMEMEVAL_MAX_SESSIONS:-12}"
SKIP_EVALUATION="${LONGMEMEVAL_SKIP_EVALUATION:-0}"
INCLUDE_TRUTHGIT_FULL_HISTORY="${LONGMEMEVAL_INCLUDE_TRUTHGIT_FULL_HISTORY:-0}"

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "OPENAI_API_KEY is required for LongMemEval comparison runs." >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Running LongMemEval random held-out comparison."
echo "sample_size=${SAMPLE_SIZE} sample_seed=${SAMPLE_SEED} answer_model=${ANSWER_MODEL} judge=${JUDGE_MODEL}"

echo
echo "[1/4] Full-history chat baseline"
LONGMEMEVAL_DATA="$DATA_FILE" \
LONGMEMEVAL_OUTPUT_DIR="$OUTPUT_DIR" \
LONGMEMEVAL_SPLIT_LABEL="$SPLIT_LABEL" \
OPENAI_MODEL="$ANSWER_MODEL" \
LONGMEMEVAL_JUDGE_MODEL="$JUDGE_MODEL" \
LONGMEMEVAL_SAMPLE_SIZE="$SAMPLE_SIZE" \
LONGMEMEVAL_SAMPLE_SEED="$SAMPLE_SEED" \
LONGMEMEVAL_READER_MODE=con \
LONGMEMEVAL_HISTORY_FORMAT=json \
LONGMEMEVAL_NO_RESUME=1 \
LONGMEMEVAL_SKIP_EVALUATION="$SKIP_EVALUATION" \
"${SCRIPT_DIR}/run_longmemeval_full.sh"

echo
echo "[2/4] TruthGit selected sessions: record_batch + beliefs_and_excerpts"
LONGMEMEVAL_DATA="$DATA_FILE" \
LONGMEMEVAL_OUTPUT_DIR="$OUTPUT_DIR" \
LONGMEMEVAL_SPLIT_LABEL="$SPLIT_LABEL" \
OPENAI_MODEL="$ANSWER_MODEL" \
LONGMEMEVAL_EXTRACTION_MODEL="$EXTRACTION_MODEL" \
LONGMEMEVAL_JUDGE_MODEL="$JUDGE_MODEL" \
LONGMEMEVAL_SAMPLE_SIZE="$SAMPLE_SIZE" \
LONGMEMEVAL_SAMPLE_SEED="$SAMPLE_SEED" \
LONGMEMEVAL_MAX_SESSIONS="$MAX_SESSIONS" \
LONGMEMEVAL_EXTRACTION_MODE=record_batch \
LONGMEMEVAL_CONTEXT_MODE=beliefs_and_excerpts \
LONGMEMEVAL_NO_RESUME=1 \
LONGMEMEVAL_SKIP_EVALUATION="$SKIP_EVALUATION" \
"${SCRIPT_DIR}/run_longmemeval_truthgit.sh"

echo
echo "[3/4] TruthGit selected sessions: per_session + beliefs_and_excerpts"
LONGMEMEVAL_DATA="$DATA_FILE" \
LONGMEMEVAL_OUTPUT_DIR="$OUTPUT_DIR" \
LONGMEMEVAL_SPLIT_LABEL="$SPLIT_LABEL" \
OPENAI_MODEL="$ANSWER_MODEL" \
LONGMEMEVAL_EXTRACTION_MODEL="$EXTRACTION_MODEL" \
LONGMEMEVAL_JUDGE_MODEL="$JUDGE_MODEL" \
LONGMEMEVAL_SAMPLE_SIZE="$SAMPLE_SIZE" \
LONGMEMEVAL_SAMPLE_SEED="$SAMPLE_SEED" \
LONGMEMEVAL_MAX_SESSIONS="$MAX_SESSIONS" \
LONGMEMEVAL_EXTRACTION_MODE=per_session \
LONGMEMEVAL_CONTEXT_MODE=beliefs_and_excerpts \
LONGMEMEVAL_NO_RESUME=1 \
LONGMEMEVAL_SKIP_EVALUATION="$SKIP_EVALUATION" \
"${SCRIPT_DIR}/run_longmemeval_truthgit.sh"

echo
echo "[4/4] TruthGit selected sessions: record_batch + beliefs_only"
LONGMEMEVAL_DATA="$DATA_FILE" \
LONGMEMEVAL_OUTPUT_DIR="$OUTPUT_DIR" \
LONGMEMEVAL_SPLIT_LABEL="$SPLIT_LABEL" \
OPENAI_MODEL="$ANSWER_MODEL" \
LONGMEMEVAL_EXTRACTION_MODEL="$EXTRACTION_MODEL" \
LONGMEMEVAL_JUDGE_MODEL="$JUDGE_MODEL" \
LONGMEMEVAL_SAMPLE_SIZE="$SAMPLE_SIZE" \
LONGMEMEVAL_SAMPLE_SEED="$SAMPLE_SEED" \
LONGMEMEVAL_MAX_SESSIONS="$MAX_SESSIONS" \
LONGMEMEVAL_EXTRACTION_MODE=record_batch \
LONGMEMEVAL_CONTEXT_MODE=beliefs_only \
LONGMEMEVAL_NO_RESUME=1 \
LONGMEMEVAL_SKIP_EVALUATION="$SKIP_EVALUATION" \
"${SCRIPT_DIR}/run_longmemeval_truthgit.sh"

if [[ "$INCLUDE_TRUTHGIT_FULL_HISTORY" == "1" ]]; then
  echo
  echo "[optional] TruthGit full history: record_batch + beliefs_and_excerpts"
  LONGMEMEVAL_DATA="$DATA_FILE" \
  LONGMEMEVAL_OUTPUT_DIR="$OUTPUT_DIR" \
  LONGMEMEVAL_SPLIT_LABEL="$SPLIT_LABEL" \
  OPENAI_MODEL="$ANSWER_MODEL" \
  LONGMEMEVAL_EXTRACTION_MODEL="$EXTRACTION_MODEL" \
  LONGMEMEVAL_JUDGE_MODEL="$JUDGE_MODEL" \
  LONGMEMEVAL_SAMPLE_SIZE="$SAMPLE_SIZE" \
  LONGMEMEVAL_SAMPLE_SEED="$SAMPLE_SEED" \
  LONGMEMEVAL_MAX_SESSIONS=0 \
  LONGMEMEVAL_EXTRACTION_MODE=record_batch \
  LONGMEMEVAL_CONTEXT_MODE=beliefs_and_excerpts \
  LONGMEMEVAL_NO_RESUME=1 \
  LONGMEMEVAL_SKIP_EVALUATION="$SKIP_EVALUATION" \
  "${SCRIPT_DIR}/run_longmemeval_truthgit.sh"
fi

echo
echo "Comparison run complete. Summaries are in ${OUTPUT_DIR}."
